name: mno_navigator
description: This package provides a DART LCP layer (native libraries not provided).
version: 0.1.0
homepage: https://github.com/Mantano/iridium
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc:
  dartx:
  dfunc:
  equatable:
  fimber:
  flutter_bloc:
  flutter_inappwebview:
  flutter_spinkit:
  photo_view:
  preload_page_view:
  rxdart:
  universal_io:

  mno_commons:
    path: ../commons
  mno_server:
    path: ../server
  mno_shared:
    path: ../shared
  mno_streamer:
    path: ../streamer
  mno_webview:
    path: ../webview

dev_dependencies:
  test:
  lints:

flutter:
  assets:
    - assets/readium/assets/
    - assets/readium/divina/
    - assets/readium/fonts/
    - assets/readium/readium-css/
    - assets/readium/readium-css/cjk-horizontal/
    - assets/readium/readium-css/cjk-vertical/
    - assets/readium/readium-css/fonts/
    - assets/readium/readium-css/rtl/
    - assets/readium/scripts/
    - assets/xpub-shared-js/
    - assets/xpub-js/
    - assets/xpub-js/controllers/
    - assets/xpub-js/model/
    - assets/xpub-js/utils/
