name: mno_shared
description: Contains the definitions of the custom types (model) used across the Readium-2 Dart projects.
version: 0.1.3
homepage: https://github.com/Mantano/mno_shared_dart
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  archive:
  collection:
  crypto:
  dartx:
  dfunc:
  equatable:
  fimber:
  http:
  image:
  intl:
  meta:
  universal_io:
  xml:
  path:
  mno_commons:
    path: ../commons

dev_dependencies:
  image_compare:
  lints:
  test:
