name: mno_streamer
version: 0.1.1
description: Streamer API and multiple file parsers (PDF, CBZ, Epub) for Dart.
homepage: https://github.com/Mantano/mno_streamer_dart
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dartx:
  dfunc:
  fimber:
  image:
  universal_io:
  xml:
  path:
  mno_commons:
    path: ../commons
  mno_shared:
    path: ../shared

dev_dependencies:
  lints:
  test:
