name: iridium_app
description: A Flutter app for eBooks
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# Managed by CodeMagic. See https://docs.codemagic.io/configuration/build-versioning/
# version: 0.0.1+2

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  iridium_reader_widget:
    path: ../reader_widget
  mno_commons:
    path: ../components/commons
  mno_navigator:
    path: ../components/navigator
  mno_opds:
    path: ../components/opds
  mno_shared:
    path: ../components/shared
  mno_webview:
    path: ../components/webview
  mno_lcp:
    path: ../components/lcp

  cached_network_image:
  cupertino_icons:
  dartx:
  dfunc:
  dio:
  fimber:
  flutter_fimber:
  flutter_font_icons:
  flutter_inappwebview:
  flutter_spinkit:
  fluttertoast:
  google_fonts:
  json_theme:
  objectdb:
  path_provider:
  permission_handler:
  provider:
  shared_preferences:
  sqflite:
  sqflite_common_ffi:
  universal_io:
  uuid:
  package_info_plus_web:
  url_launcher_web:

dependency_overrides:
  shared_preferences_windows: 2.1.2

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/appainter_light_theme.json
    - assets/appainter_dark_theme.json
