name: example
description: Example.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  mno_commons:
    path: ../

dev_dependencies:
  lints: ^2.0.0

dependency_overrides:
  path: ^1.8.3
