name: mno_lcp
description: This package provides a DART LCP layer (native libraries not provided).
version: 0.1.0
homepage: https://github.com/Mantano/mno_lcp_dart
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  crypto: ^3.0.2
  dartx: ^1.1.0
  device_info_plus: ^3.2.4
  dfunc: ^0.8.0+1
  ffi: ^2.0.1
  fimber: ^0.6.6
  flutter_archive: ^5.0.0
  intl: ^0.17.0
  mno_fsm: ^0.1.2
  multiple_localization: ^0.3.0
  path: ^1.8.2
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  sqflite: ^2.0.3+1
  universal_io: ^2.0.4
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  mno_commons:
    path: ../commons
  mno_shared:
    path: ../shared

dependency_overrides:
  ffi: ^2.0.1

dev_dependencies:
  test: ^1.21.5
  lints: ^2.0.0

assets:
  - assets/
