name: mno_lcp
description: This package provides a DART LCP layer (native libraries not provided).
version: 0.1.0
homepage: https://github.com/Mantano/mno_lcp_dart
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection:
  crypto:
  dartx:
  device_info_plus:
  dfunc:
  ffi:
  fimber:
  flutter_archive:
  intl:
  mno_fsm:
  multiple_localization:
  path:
  path_provider:
  shared_preferences:
  sqflite:
  universal_io:
  url_launcher:
  uuid:
  mno_commons:
    path: ../commons
  mno_shared:
    path: ../shared

dev_dependencies:
  test:
  lints:

assets:
  - assets/
