name: mno_server
description: Contains the server functions to serve resources in the webview.
version: 0.1.0
homepage: https://github.com/Mantano/mno_server_dart
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mno_commons:
    path: ../commons
  mno_shared:
    path: ../shared
  mno_streamer:
    path: ../streamer
  mno_webview:
    path: ../webview
  bloc:
  dartx:
  dfunc:
  equatable:
  fimber:
  flutter_inappwebview:
  intl:
  meta:
  path:
  rxdart:
  universal_io:

dev_dependencies:
  lints:
