name: mno_commons
description: This package provide utilities (JSON, io, Href, UriTemplate, etc...) for other mno_xxx packages.
version: 0.1.2
homepage: https://github.com/Mantano/mno_commons_dart
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  archive:
  crypto:
  dartx:
  dfunc:
  fimber:
  path:
  universal_io:

dev_dependencies:
  lints:
  test:
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
