name: mno_commons
description: This package provide utilities (JSON, io, Href, UriTemplate, etc...) for other mno_xxx packages.
version: 0.1.2
homepage: https://github.com/Mantano/mno_commons_dart
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  archive: ^3.3.5
  crypto: ^3.0.2
  dartx: ^1.1.0
  dfunc: ^0.8.1
  fimber: ^0.6.6
  path: ^1.8.3
  universal_io: ^2.0.4

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
