name: mno_opds
description: Contains OPDS1 and OPDS2 parsers using OPDS classes provided by mno_shared.
version: 0.1.1
homepage: https://github.com/Mantano/mno_opds_dart
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dartx:
  dfunc:
  fimber:
  http:
  universal_io:
  xml:
  mno_commons:
    path: ../commons
  mno_shared:
    path: ../shared

dev_dependencies:
  lints:
  test:
