name: iridium_reader_widget
description: Plug and play ebook reader widget
version: 0.0.1
publish_to: none
homepage: https://iridium.rocks

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  mno_commons:
    path: ../components/commons
  mno_navigator:
    path: ../components/navigator
  mno_opds:
    path: ../components/opds
  mno_server:
    path: ../components/server
  mno_shared:
    path: ../components/shared
  mno_streamer:
    path: ../components/streamer
  mno_webview:
    path: ../components/webview
  cupertino_icons:
  dartx:
  dfunc:
  fimber:
  flutter_bloc:
  flutter_fimber:
  flutter_inappwebview:
  flutter_spinkit:
  fluttertoast:
  path_provider:
  flutter_xlider:
    git:
      url: https://github.com/Ali-Azmoud/flutter_xlider.git
      ref: master # branch name

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
